#!/bin/sh
# Program:
#   Test script for GB-Tree
# History:
# 2014/5/10  edward liu  v1.0

#define some variables
DATA_DIRECTORY=data/
BENCHMARK_DIRECTORY=benchmark/
INDEX_EXTENSION=.idx
TABLE_EXTENSION=.tbl
DATA_FILE_EXTENSION=.txt
POINT_QUERY=point
SEPERATOR=_
i=0

# test point query algorithm
echo -e "start testing point query algorithm..."
echo -e "data set: small"
NAME=small
FILE="$BENCHMARK_DIRECTORY$POINT_QUERY$SEPERATOR$NAME$DATA_FILE_EXTENSION"
rm -f "$DATA_DIRECTORY$NAME$INDEX_EXTENSION" "$DATA_DIRECTORY$NAME$TABLE_EXTENSION"

./gbtree $NAME "$DATA_DIRECTORY$NAME$DATA_FILE_EXTENSION" $POINT_QUERY > "$FILE"
while [ "$i" != "4" ]
do
	rm -f "$DATA_DIRECTORY$NAME$INDEX_EXTENSION" "$DATA_DIRECTORY$NAME$TABLE_EXTENSION"
	./gbtree $NAME "$DATA_DIRECTORY$NAME$DATA_FILE_EXTENSION" $POINT_QUERY >> "$FILE"
	i=$(($i+1))
done
echo -e "end small"
echo -e "data set: middle"
NAME=middle
i=0
FILE="$BENCHMARK_DIRECTORY$POINT_QUERY$SEPERATOR$NAME$DATA_FILE_EXTENSION"
rm -f "$DATA_DIRECTORY$NAME$INDEX_EXTENSION" "$DATA_DIRECTORY$NAME$TABLE_EXTENSION"

./gbtree $NAME "$DATA_DIRECTORY$NAME$DATA_FILE_EXTENSION" $POINT_QUERY > "$FILE"
while [ "$i" != "4" ]
do
	rm -f "$DATA_DIRECTORY$NAME$INDEX_EXTENSION" "$DATA_DIRECTORY$NAME$TABLE_EXTENSION"
	./gbtree $NAME "$DATA_DIRECTORY$NAME$DATA_FILE_EXTENSION" $POINT_QUERY >> "$FILE"
	i=$(($i+1))
done
echo -e "end middle"
echo -e "data set: large"
NAME=large
i=0
FILE="$BENCHMARK_DIRECTORY$POINT_QUERY$SEPERATOR$NAME$DATA_FILE_EXTENSION"
rm -f "$DATA_DIRECTORY$NAME$INDEX_EXTENSION" "$DATA_DIRECTORY$NAME$TABLE_EXTENSION"

./gbtree $NAME "$DATA_DIRECTORY$NAME$DATA_FILE_EXTENSION" $POINT_QUERY > "$FILE"
while [ "$i" != "4" ]
do
	rm -f "$DATA_DIRECTORY$NAME$INDEX_EXTENSION" "$DATA_DIRECTORY$NAME$TABLE_EXTENSION"
	./gbtree $NAME "$DATA_DIRECTORY$NAME$DATA_FILE_EXTENSION" $POINT_QUERY >> "$FILE"
	i=$(($i+1))
done
echo -e "end large"
echo -e "data set: xlarge"
NAME=xlarge
i=0
FILE="$BENCHMARK_DIRECTORY$POINT_QUERY$SEPERATOR$NAME$DATA_FILE_EXTENSION"
rm -f "$DATA_DIRECTORY$NAME$INDEX_EXTENSION" "$DATA_DIRECTORY$NAME$TABLE_EXTENSION"

./gbtree $NAME "$DATA_DIRECTORY$NAME$DATA_FILE_EXTENSION" $POINT_QUERY > "$FILE"
while [ "$i" != "4" ]
do
	rm -f "$DATA_DIRECTORY$NAME$INDEX_EXTENSION" "$DATA_DIRECTORY$NAME$TABLE_EXTENSION"
	./gbtree $NAME "$DATA_DIRECTORY$NAME$DATA_FILE_EXTENSION" $POINT_QUERY >> "$FILE"
	i=$(($i+1))
done
echo -e "end xlarge"
echo -e "data set: xxlarge"
NAME=xxlarge
i=0
FILE="$BENCHMARK_DIRECTORY$POINT_QUERY$SEPERATOR$NAME$DATA_FILE_EXTENSION"
rm -f "$DATA_DIRECTORY$NAME$INDEX_EXTENSION" "$DATA_DIRECTORY$NAME$TABLE_EXTENSION"

./gbtree $NAME "$DATA_DIRECTORY$NAME$DATA_FILE_EXTENSION" $POINT_QUERY > "$FILE"
while [ "$i" != "4" ]
do
	rm -f "$DATA_DIRECTORY$NAME$INDEX_EXTENSION" "$DATA_DIRECTORY$NAME$TABLE_EXTENSION"
	./gbtree $NAME "$DATA_DIRECTORY$NAME$DATA_FILE_EXTENSION" $POINT_QUERY >> "$FILE"
	i=$(($i+1))
done
echo -e "end xxlarge"
echo -e "data set: xxxlarge"
NAME=xxxlarge
i=0
FILE="$BENCHMARK_DIRECTORY$POINT_QUERY$SEPERATOR$NAME$DATA_FILE_EXTENSION"
rm -f "$DATA_DIRECTORY$NAME$INDEX_EXTENSION" "$DATA_DIRECTORY$NAME$TABLE_EXTENSION"

./gbtree $NAME "$DATA_DIRECTORY$NAME$DATA_FILE_EXTENSION" $POINT_QUERY > "$FILE"
while [ "$i" != "4" ]
do
	rm -f "$DATA_DIRECTORY$NAME$INDEX_EXTENSION" "$DATA_DIRECTORY$NAME$TABLE_EXTENSION"
	./gbtree $NAME "$DATA_DIRECTORY$NAME$DATA_FILE_EXTENSION" $POINT_QUERY >> "$FILE"
	i=$(($i+1))
done
echo -e "end xxxlarge"
echo -e "testing point query algorithm ends"
