#!/bin/sh
# Program:
#   Test script for GB-Tree
# History:
# 2014/5/10  edward liu  v1.0

#define some variables
DATA_DIRECTORY=data/
BENCHMARK_DIRECTORY=benchmark/
INDEX_EXTENSION=.idx
TABLE_EXTENSION=.tbl
DATA_FILE_EXTENSION=.txt
POINT_QUERY=point
RANGE_QUERY=range
NEAREST_QUERY=nearest
SEPERATOR=_
SHELL_NAME=run
NAME=xlarge
i=0
if [ "$1" = "1" ]; then
	echo -e "start runing point query..."
	echo -e "data set: $NAME"
	FILE="$BENCHMARK_DIRECTORY$POINT_QUERY$SEPERATOR$NAME$SEPERATOR$SHELL_NAME$DATA_FILE_EXTENSION"
	rm -f "$DATA_DIRECTORY$NAME$INDEX_EXTENSION" "$DATA_DIRECTORY$NAME$TABLE_EXTENSION"
	
	./gbtree $NAME "$DATA_DIRECTORY$NAME$DATA_FILE_EXTENSION" $POINT_QUERY > "$FILE"
elif [ "$1" = "2" ]; then
	echo -e "start runing range query..."
	echo -e "data set: $NAME"
	FILE="$BENCHMARK_DIRECTORY$RANGE_QUERY$SEPERATOR$TABLE_NAME$SEPERATOR$SHELL_NAME$DATA_FILE_EXTENSION"
	rm -f "$DATA_DIRECTORY$TABLE_NAME$INDEX_EXTENSION" "$DATA_DIRECTORY$TABLE_NAME$TABLE_EXTENSION"
	
	./gbtree $TABLE_NAME "$DATA_DIRECTORY$TABLE_NAME$DATA_FILE_EXTENSION" $RANGE_QUERY >> "$FILE"
else
	echo -e "start runing nearest query..."
	echo -e "data set: $NAME"
	FILE="$BENCHMARK_DIRECTORY$NEAREST_QUERY$SEPERATOR$NAME$SEPERATOR$SHELL_NAME$DATA_FILE_EXTENSION"
	rm -f "$DATA_DIRECTORY$NAME$INDEX_EXTENSION" "$DATA_DIRECTORY$NAME$TABLE_EXTENSION"
	
	./gbtree $NAME "$DATA_DIRECTORY$NAME$DATA_FILE_EXTENSION" $NEAREST_QUERY >> "$FILE"
fi
